import {
  Business,
  BusinessHours,
  UserProfile,
  Professional,
  Client,
  Service,
  Appointment,
  Sale,
  CashRegister,
  CashTransaction,
  Expense,
  Commission,
  LoyaltyProgram,
  LoyaltyCard,
  LoyaltyTransaction,
  GalleryItem,
  Anamnese,
  MarketingCampaign,
  CrmAutomationRule,
  CrmTask,
  CrmNotification,
} from '../types';

export const DEMO_BUSINESS_ID = 'biz-demo-studioflow';

export const initialBusiness: Business = {
  id: DEMO_BUSINESS_ID,
  name: 'StudioFlow Beauty & Barber',
  type: 'Barbearia + Salão',
  owner_name: 'Gabriel Santos',
  email: 'contato@studioflow.app',
  phone: '(11) 3456-7890',
  whatsapp: '11988887777',
  address: 'Av. Paulista, 1000 - Bela Vista',
  city: 'São Paulo',
  state: 'SP',
  zip_code: '01310-100',
  slug: 'studioflow-demo',
  plan: 'professional',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  cancellation_policy: 'Cancelamentos sem custo com até 2h de antecedência.',
  min_advance_time_hours: 1,
  slot_duration_minutes: 30,
};

export const initialBusinessHours: BusinessHours[] = [
  { id: 'bh-0', business_id: DEMO_BUSINESS_ID, day_of_week: 0, open_time: '09:00', close_time: '14:00', is_open: false },
  { id: 'bh-1', business_id: DEMO_BUSINESS_ID, day_of_week: 1, open_time: '09:00', close_time: '20:00', is_open: true },
  { id: 'bh-2', business_id: DEMO_BUSINESS_ID, day_of_week: 2, open_time: '09:00', close_time: '20:00', is_open: true },
  { id: 'bh-3', business_id: DEMO_BUSINESS_ID, day_of_week: 3, open_time: '09:00', close_time: '20:00', is_open: true },
  { id: 'bh-4', business_id: DEMO_BUSINESS_ID, day_of_week: 4, open_time: '09:00', close_time: '20:00', is_open: true },
  { id: 'bh-5', business_id: DEMO_BUSINESS_ID, day_of_week: 5, open_time: '08:00', close_time: '21:00', is_open: true },
  { id: 'bh-6', business_id: DEMO_BUSINESS_ID, day_of_week: 6, open_time: '08:00', close_time: '20:00', is_open: true },
];

export const initialProfiles: UserProfile[] = [
  {
    id: 'user-owner-1',
    business_id: DEMO_BUSINESS_ID,
    name: 'Gabriel Santos',
    email: 'admin@studioflow.app',
    role: 'OWNER',
    phone: '11988887777',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-prof-1',
    business_id: DEMO_BUSINESS_ID,
    name: 'Carlos Andrade',
    email: 'carlos@studioflow.app',
    role: 'PROFESSIONAL',
    professional_id: 'prof-carlos',
    phone: '11977771111',
    created_at: new Date().toISOString(),
  },
];

export const initialProfessionals: Professional[] = [
  {
    id: 'prof-carlos',
    business_id: DEMO_BUSINESS_ID,
    name: 'Carlos Andrade',
    phone: '(11) 97777-1111',
    whatsapp: '11977771111',
    email: 'carlos@studioflow.app',
    specialty: 'Barbeiro Master & Visagista',
    commission_rate: 40,
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prof-fernanda',
    business_id: DEMO_BUSINESS_ID,
    name: 'Fernanda Lima',
    phone: '(11) 97777-2222',
    whatsapp: '11977772222',
    email: 'fernanda@studioflow.app',
    specialty: 'Hairstylist & Colorista',
    commission_rate: 50,
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prof-ana',
    business_id: DEMO_BUSINESS_ID,
    name: 'Ana Paula',
    phone: '(11) 97777-3333',
    whatsapp: '11977773333',
    email: 'ana@studioflow.app',
    specialty: 'Nail Designer & Manicure',
    commission_rate: 45,
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prof-joao',
    business_id: DEMO_BUSINESS_ID,
    name: 'João Pedro',
    phone: '(11) 97777-4444',
    whatsapp: '11977774444',
    email: 'joao@studioflow.app',
    specialty: 'Especialista em Barba Terapia',
    commission_rate: 40,
    status: 'active',
    created_at: new Date().toISOString(),
  },
];

export const initialServices: Service[] = [
  {
    id: 'srv-corte-masc',
    business_id: DEMO_BUSINESS_ID,
    category: 'Barbearia',
    name: 'Corte Masculino',
    description: 'Corte moderno com lavagem, finalização e secagem.',
    price: 50,
    duration_minutes: 30,
    commission_rate: 40,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-barba',
    business_id: DEMO_BUSINESS_ID,
    category: 'Barbearia',
    name: 'Barba Terapia',
    description: 'Modelagem de barba com toalha quente e óleos essenciais.',
    price: 40,
    duration_minutes: 30,
    commission_rate: 40,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-combo-corte-barba',
    business_id: DEMO_BUSINESS_ID,
    category: 'Barbearia',
    name: 'Corte + Barba (Combo)',
    description: 'Combo completo de cabelo e barba com atendimento vip.',
    price: 80,
    duration_minutes: 50,
    commission_rate: 40,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-corte-fem',
    business_id: DEMO_BUSINESS_ID,
    category: 'Cabelo',
    name: 'Corte Feminino',
    description: 'Corte estilizado com escova e tratamento hidratante.',
    price: 90,
    duration_minutes: 45,
    commission_rate: 50,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-escova',
    business_id: DEMO_BUSINESS_ID,
    category: 'Cabelo',
    name: 'Escova Modelada',
    description: 'Lavagem especial e escova modelada duradoura.',
    price: 60,
    duration_minutes: 40,
    commission_rate: 50,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-manicure',
    business_id: DEMO_BUSINESS_ID,
    category: 'Manicure',
    name: 'Manicure Completa',
    description: 'Cutilagem, cutilagem profunda, esmaltação e hidratação.',
    price: 35,
    duration_minutes: 30,
    commission_rate: 45,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-pedicure',
    business_id: DEMO_BUSINESS_ID,
    category: 'Pedicure',
    name: 'Pedicure Spa',
    description: 'Spa dos pés com esfoliação, massagem e esmaltação.',
    price: 45,
    duration_minutes: 40,
    commission_rate: 45,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-sobrancelha',
    business_id: DEMO_BUSINESS_ID,
    category: 'Sobrancelha',
    name: 'Design de Sobrancelhas',
    description: 'Design personalizado com simetria facial.',
    price: 35,
    duration_minutes: 25,
    commission_rate: 40,
    active: true,
    created_at: new Date().toISOString(),
  },
];

const todayStr = new Date().toISOString().slice(0, 10);
const todayYearMonth = todayStr.slice(0, 7);

export const initialClients: Client[] = [
  {
    id: 'cli-joao',
    business_id: DEMO_BUSINESS_ID,
    name: 'João Silva',
    phone: '(11) 99999-1111',
    whatsapp: '11999991111',
    email: 'joao.silva@gmail.com',
    birth_date: `${todayYearMonth}-15`,
    notes: 'Gosta de café expresso sem açúcar e degradê navalhado.',
    total_appointments: 8,
    total_spent: 640,
    last_appointment_at: todayStr,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cli-maria',
    business_id: DEMO_BUSINESS_ID,
    name: 'Maria Souza',
    phone: '(11) 99999-2222',
    whatsapp: '11999992222',
    email: 'maria.souza@gmail.com',
    birth_date: `${todayYearMonth}-20`,
    notes: 'Alergia a tintura com amônia. Prefere produtos veganos.',
    total_appointments: 10,
    total_spent: 900,
    last_appointment_at: todayStr,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cli-carlos',
    business_id: DEMO_BUSINESS_ID,
    name: 'Carlos Santos',
    phone: '(11) 99999-3333',
    whatsapp: '11999993333',
    email: 'carlos.santos@gmail.com',
    birth_date: '1992-05-12',
    notes: 'Cliente super pontual.',
    total_appointments: 9,
    total_spent: 720,
    last_appointment_at: todayStr,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cli-ana',
    business_id: DEMO_BUSINESS_ID,
    name: 'Ana Oliveira',
    phone: '(11) 99999-4444',
    whatsapp: '11999994444',
    email: 'ana.oliveira@outlook.com',
    birth_date: `${todayYearMonth}-08`, // Birthday today/this month!
    notes: 'Faz manicure semanalmente.',
    total_appointments: 2,
    total_spent: 70,
    last_appointment_at: todayStr,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cli-rodrigo',
    business_id: DEMO_BUSINESS_ID,
    name: 'Rodrigo Lima',
    phone: '(11) 99999-5555',
    whatsapp: '11999995555',
    email: 'rodrigo.lima@yahoo.com',
    birth_date: '1995-11-03',
    notes: 'Atendido por Carlos.',
    total_appointments: 1,
    total_spent: 50,
    last_appointment_at: todayStr,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cli-lucas',
    business_id: DEMO_BUSINESS_ID,
    name: 'Lucas Almeida',
    phone: '(11) 99999-6666',
    whatsapp: '11999996666',
    email: 'lucas.almeida@hotmail.com',
    birth_date: '1988-03-22',
    notes: 'Cliente sumido - enviar convite de retorno.',
    total_appointments: 4,
    total_spent: 280,
    last_appointment_at: '2026-06-15', // Inactive > 45 days
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: 'apt-1',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-joao',
    client_name: 'João Silva',
    client_whatsapp: '11999991111',
    professional_id: 'prof-carlos',
    professional_name: 'Carlos Andrade',
    service_id: 'srv-combo-corte-barba',
    service_name: 'Corte + Barba (Combo)',
    date: todayStr,
    start_time: '09:00',
    end_time: '09:50',
    duration_minutes: 50,
    price: 80,
    commission_amount: 32,
    status: 'CONCLUÍDO',
    notes: 'Atendimento concluído e pago no PIX.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'apt-2',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-maria',
    client_name: 'Maria Souza',
    client_whatsapp: '11999992222',
    professional_id: 'prof-fernanda',
    professional_name: 'Fernanda Lima',
    service_id: 'srv-escova',
    service_name: 'Escova Modelada',
    date: todayStr,
    start_time: '10:00',
    end_time: '10:40',
    duration_minutes: 40,
    price: 60,
    commission_amount: 30,
    status: 'CONCLUÍDO',
    notes: 'Cliente completou 10 atendimentos - Cartão Fidelidade!',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'apt-3',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-carlos',
    client_name: 'Carlos Santos',
    client_whatsapp: '11999993333',
    professional_id: 'prof-joao',
    professional_name: 'João Pedro',
    service_id: 'srv-barba',
    service_name: 'Barba Terapia',
    date: todayStr,
    start_time: '11:30',
    end_time: '12:00',
    duration_minutes: 30,
    price: 40,
    commission_amount: 16,
    status: 'EM_ATENDIMENTO',
    notes: 'Em andamento no lavatório.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'apt-4',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-ana',
    client_name: 'Ana Oliveira',
    client_whatsapp: '11999994444',
    professional_id: 'prof-ana',
    professional_name: 'Ana Paula',
    service_id: 'srv-manicure',
    service_name: 'Manicure Completa',
    date: todayStr,
    start_time: '14:00',
    end_time: '14:30',
    duration_minutes: 30,
    price: 35,
    commission_amount: 15.75,
    status: 'CONFIRMADO',
    notes: 'Confirmado via WhatsApp.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'apt-5',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-rodrigo',
    client_name: 'Rodrigo Lima',
    client_whatsapp: '11999995555',
    professional_id: 'prof-carlos',
    professional_name: 'Carlos Andrade',
    service_id: 'srv-corte-masc',
    service_name: 'Corte Masculino',
    date: todayStr,
    start_time: '15:30',
    end_time: '16:00',
    duration_minutes: 30,
    price: 50,
    commission_amount: 20,
    status: 'AGENDADO',
    notes: 'Aniversariante do mês.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const initialLoyaltyProgram: LoyaltyProgram = {
  id: 'loyalty-prog-1',
  business_id: DEMO_BUSINESS_ID,
  is_active: true,
  required_stamps: 10,
  reward_description: '1 Corte Masculino ou Escova Grátis',
  discount_type: 'free_service',
  discount_value: 100,
  validity_days: 90,
};

export const initialLoyaltyCards: LoyaltyCard[] = [
  {
    id: 'loyalty-card-joao',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-joao',
    client_name: 'João Silva',
    current_stamps: 8,
    total_completed: 0,
    reward_available: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'loyalty-card-maria',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-maria',
    client_name: 'Maria Souza',
    current_stamps: 10,
    total_completed: 1,
    reward_available: true, // REWARD READY!
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'loyalty-card-carlos',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-carlos',
    client_name: 'Carlos Santos',
    current_stamps: 9, // ALMOST THERE! (9/10)
    total_completed: 0,
    reward_available: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const initialCashRegister: CashRegister = {
  id: 'cash-reg-today',
  business_id: DEMO_BUSINESS_ID,
  opened_at: `${todayStr}T08:00:00.000Z`,
  initial_amount: 150.0,
  final_amount_expected: 290.0,
  status: 'OPEN',
  opened_by_name: 'Gabriel Santos',
  sales_summary: {
    dinheiro: 50.0,
    pix: 140.0,
    debito: 0.0,
    credito: 0.0,
    total: 190.0,
  },
};

export const initialCashTransactions: CashTransaction[] = [
  {
    id: 'tx-1',
    cash_register_id: 'cash-reg-today',
    business_id: DEMO_BUSINESS_ID,
    type: 'ENTRY',
    description: 'Venda Corte + Barba - João Silva',
    amount: 80.0,
    payment_method: 'pix',
    created_at: `${todayStr}T09:55:00.000Z`,
  },
  {
    id: 'tx-2',
    cash_register_id: 'cash-reg-today',
    business_id: DEMO_BUSINESS_ID,
    type: 'ENTRY',
    description: 'Venda Escova Modelada - Maria Souza',
    amount: 60.0,
    payment_method: 'pix',
    created_at: `${todayStr}T10:45:00.000Z`,
  },
  {
    id: 'tx-3',
    cash_register_id: 'cash-reg-today',
    business_id: DEMO_BUSINESS_ID,
    type: 'SANGRIA',
    description: 'Retirada para compras de água e café',
    amount: 25.0,
    payment_method: 'dinheiro',
    created_at: `${todayStr}T11:00:00.000Z`,
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    business_id: DEMO_BUSINESS_ID,
    category: 'Aluguel',
    description: 'Aluguel comercial mês atual',
    amount: 2500,
    date: `${todayYearMonth}-01`,
    status: 'PAGO',
    created_at: new Date().toISOString(),
  },
  {
    id: 'exp-2',
    business_id: DEMO_BUSINESS_ID,
    category: 'Internet',
    description: 'Fibra Óptica 600MB',
    amount: 150,
    date: `${todayYearMonth}-05`,
    status: 'PAGO',
    created_at: new Date().toISOString(),
  },
  {
    id: 'exp-3',
    business_id: DEMO_BUSINESS_ID,
    category: 'Produtos',
    description: 'Lote de pomadas e shampoo de barba',
    amount: 450,
    date: `${todayYearMonth}-07`,
    status: 'PENDENTE',
    created_at: new Date().toISOString(),
  },
];

export const initialCommissions: Commission[] = [
  {
    id: 'com-1',
    business_id: DEMO_BUSINESS_ID,
    professional_id: 'prof-carlos',
    professional_name: 'Carlos Andrade',
    service_name: 'Corte + Barba (Combo)',
    service_price: 80,
    percentage: 40,
    amount: 32,
    date: todayStr,
    status: 'PENDENTE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'com-2',
    business_id: DEMO_BUSINESS_ID,
    professional_id: 'prof-fernanda',
    professional_name: 'Fernanda Lima',
    service_name: 'Escova Modelada',
    service_price: 60,
    percentage: 50,
    amount: 30,
    date: todayStr,
    status: 'PENDENTE',
    created_at: new Date().toISOString(),
  },
];

export const initialGallery: GalleryItem[] = [
  {
    id: 'gal-1',
    business_id: DEMO_BUSINESS_ID,
    title: 'Fade Navalhado com Barba Terapia',
    category: 'Cortes',
    image_url: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=600&q=80',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gal-2',
    business_id: DEMO_BUSINESS_ID,
    title: 'Design de Barba e Alinhamento',
    category: 'Barbas',
    image_url: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=600&q=80',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gal-3',
    business_id: DEMO_BUSINESS_ID,
    title: 'Escova e Morena Iluminada',
    category: 'Cabelos',
    image_url: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=600&q=80',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gal-4',
    business_id: DEMO_BUSINESS_ID,
    title: 'Nail Art Minimalista',
    category: 'Unhas',
    image_url: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80',
    created_at: new Date().toISOString(),
  },
];

export const initialAnamnese: Anamnese[] = [
  {
    id: 'ana-1',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-maria',
    hair_type: 'Ondulado 2B, finos e sensibilizados',
    chemical_history: 'Luzes há 3 meses. Sem progressiva.',
    allergies: 'Sensibilidade a amônia e parabenos.',
    preferences: 'Gosta de acabamento natural e produtos com óleo de argan.',
    notes: 'Recomendar cronograma capilar de nutrição.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ana-2',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-joao',
    hair_type: 'Cabelo grosso e barba densa',
    chemical_history: 'Nenhuma química',
    allergies: 'Nenhuma relata',
    preferences: 'Toalha quente com essência de menta',
    notes: 'Pele sensível no pescoço - usar lâmina nova e óleo pre-shave.',
    updated_at: new Date().toISOString(),
  },
];

export const initialMarketingCampaigns: MarketingCampaign[] = [
  {
    id: 'camp-reativacao-demo',
    business_id: DEMO_BUSINESS_ID,
    title: 'Reativação de Clientes Sumidos',
    description: 'Oferecer convite de retorno especial para clientes em risco e inativos.',
    campaign_type: 'REACTIVATION',
    segment: 'EM_RISCO',
    message_template: 'Olá {{nome}}, sentimos sua falta na {{empresa}}! Preparamos uma condição especial para seu próximo {{servico}}. Que tal agendar seu horário?',
    status: 'ACTIVE',
    start_date: new Date().toISOString().slice(0, 10),
    sent_count: 5,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'camp-aniversario-demo',
    business_id: DEMO_BUSINESS_ID,
    title: 'Aniversariantes do Mês',
    description: 'Campanha de relacionamento com felicitações e presente de aniversário.',
    campaign_type: 'BIRTHDAY',
    segment: 'ANIVERSARIANTES',
    message_template: 'Feliz Aniversário, {{nome}}! 🎉 Toda a equipe da {{empresa}} te deseja um dia fantástico. Venha comemorar conosco com um presente especial!',
    status: 'ACTIVE',
    advance_days: 7,
    sent_count: 2,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'camp-vip-demo',
    business_id: DEMO_BUSINESS_ID,
    title: 'Reconhecimento Clientes VIP',
    description: 'Agradecimento e prioridade de agendamento para clientes de alto valor.',
    campaign_type: 'RELATIONSHIP',
    segment: 'ALTO_VALOR',
    message_template: 'Olá {{nome}}, você é um cliente especial na {{empresa}}! Como agradecimento por sua parceria, reservamos horários exclusivos para seu {{servico}} este mês.',
    status: 'DRAFT',
    sent_count: 0,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

export const initialCrmAutomationRules: CrmAutomationRule[] = [
  {
    id: 'rule-reativacao-risco',
    business_id: DEMO_BUSINESS_ID,
    name: 'Alerta de Cliente em Risco (46-90 dias)',
    event_type: 'CUSTOMER_AT_RISK',
    is_active: true,
    period_days: 45,
    message_template: 'Olá {{nome}}, sentindo sua falta na {{empresa}}! Que tal agendar seu {{servico}} esta semana com condições especiais?',
    action_type: 'CREATE_TASK',
    created_at: new Date().toISOString(),
  },
  {
    id: 'rule-sem-proximo-agendamento',
    business_id: DEMO_BUSINESS_ID,
    name: 'Atendimento Concluído sem Novo Agendamento',
    event_type: 'CUSTOMER_WITHOUT_FUTURE_APPOINTMENT',
    is_active: true,
    period_days: 0,
    message_template: 'Olá {{nome}}, agradecemos a visita na {{empresa}}! Gostaria de deixar garantido seu próximo horário para {{servico}}?',
    action_type: 'CREATE_TASK',
    created_at: new Date().toISOString(),
  },
  {
    id: 'rule-aniversariante',
    business_id: DEMO_BUSINESS_ID,
    name: 'Parabéns Aniversariantes do Mês',
    event_type: 'BIRTHDAY_APPROACHING',
    is_active: true,
    period_days: 7,
    message_template: 'Feliz Aniversário, {{nome}}! 🎉 Toda a equipe da {{empresa}} deseja um dia incrível! Venha comemorar conosco com um presente exclusivo!',
    action_type: 'CREATE_TASK',
    created_at: new Date().toISOString(),
  },
  {
    id: 'rule-fidelidade-recompensa',
    business_id: DEMO_BUSINESS_ID,
    name: 'Recompensa de Fidelidade Disponível',
    event_type: 'LOYALTY_REWARD_AVAILABLE',
    is_active: true,
    period_days: 0,
    message_template: 'Parabéns {{nome}}! Você completou seu cartão fidelidade na {{empresa}} e tem um prêmio especial aguardando por você!',
    action_type: 'CREATE_TASK',
    created_at: new Date().toISOString(),
  },
  {
    id: 'rule-cliente-vip',
    business_id: DEMO_BUSINESS_ID,
    name: 'Reconhecimento Cliente VIP',
    event_type: 'CUSTOMER_HIGH_VALUE',
    is_active: true,
    period_days: 0,
    message_template: 'Olá {{nome}}, você é um cliente VIP na {{empresa}}! Separamos horários prioritários e mimos especiais para sua próxima visita.',
    action_type: 'CREATE_TASK',
    created_at: new Date().toISOString(),
  },
];

export const initialCrmTasks: CrmTask[] = [
  {
    id: 'task-demo-1',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-maria',
    client_name: 'Maria Oliveira',
    rule_id: 'rule-reativacao-risco',
    origin_event: 'CUSTOMER_AT_RISK',
    title: 'Reativar cliente Maria Oliveira (Em risco há 52 dias)',
    description: 'Cliente realizou Coloração há 52 dias e não possui agendamento futuro. Entrar em contato via WhatsApp.',
    status: 'PENDING',
    priority: 'HIGH',
    due_date: new Date(Date.now() + 2 * 86400000).toISOString().slice(0, 10),
    assigned_to: 'Gerência StudioFlow',
    dedup_key: `${DEMO_BUSINESS_ID}:cli-maria:CUSTOMER_AT_RISK:${new Date().toISOString().slice(0, 7)}`,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'task-demo-2',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-joao',
    client_name: 'João Silva',
    rule_id: 'rule-sem-proximo-agendamento',
    origin_event: 'CUSTOMER_WITHOUT_FUTURE_APPOINTMENT',
    title: 'Garantir próximo agendamento do cliente João Silva',
    description: 'Atendimento de Corte Barba concluído recentemente, porém cliente ainda não possui horário agendado.',
    status: 'IN_PROGRESS',
    priority: 'NORMAL',
    due_date: new Date(Date.now() + 86400000).toISOString().slice(0, 10),
    assigned_to: 'Recepção',
    dedup_key: `${DEMO_BUSINESS_ID}:cli-joao:CUSTOMER_WITHOUT_FUTURE_APPOINTMENT:${new Date().toISOString().slice(0, 7)}`,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

export const initialCrmNotifications: CrmNotification[] = [
  {
    id: 'notif-demo-1',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-maria',
    title: 'Oportunidade CRM: Cliente em Risco',
    message: 'Maria Oliveira completou 52 dias sem visita. Tarefa de reativação gerada automaticamente.',
    type: 'opportunity',
    read: false,
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-demo-2',
    business_id: DEMO_BUSINESS_ID,
    client_id: 'cli-joao',
    title: 'Pós-Atendimento: Sem Próximo Agendamento',
    message: 'João Silva concluiu atendimento sem marcar o próximo retorno.',
    type: 'opportunity',
    read: false,
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
];
